config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  root 'restaurants#index'

  resources:restaurants

  resources :restaurants do
    resources :reviews
  end

  resources :reviews do
    resources :endorsements
  end

end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
  belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

	has_many :reviews, dependent: :destroy
	belongs_to :user
	validates :name, presence: true, uniqueness: true, length: { minimum: 3 }
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "images/:style/missing.png",
                    :storage => :s3,
                    :s3_credentials => Proc.new{|a| a.instance.s3_credentials }

  def s3_credentials
    { :bucket => "yelp-elewis", :access_key_id => Rails.application.secrets.access_key_id, :secret_access_key => Rails.application.secrets.secret_access_key }
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :user
	has_many :endorsements
	
		validates :rating, inclusion: (1..5)

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :reviews
  has_many :endorsements
  has_many :restaurants

def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.image = auth.info.image # assuming the user model has an image
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

	include ActionView::Helpers::TextHelper

	before_action :authenticate_user!

	def create
		@review = Review.find(params[:review_id])
		@review.endorsements.create
		render json: { new_endorsement_count: pluralize(@review.endorsements.count, 'endorsement')}
	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	before_action :authenticate_user!, :except => [:show, :index]  

	def index
		@restaurants = Restaurant.all
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurant = Restaurant.create(params[:restaurant].permit(:name, :description, :image))
		@restaurant.user_id = current_user.id
		@restaurant.save
		redirect_to restaurants_path
	end

	def show
		@restaurant = Restaurant.find(params[:id])
	end

	def edit
		@restaurant = Restaurant.find(params[:id])
		if @restaurant.user_id == current_user.id
			render 'edit'
		else
			redirect_to restaurants_path
		end
	end

	def update
		@restaurant = Restaurant.find(params[:id])


		if @restaurant.update(params[:restaurant].permit(:name, :description, :image))
			redirect_to restaurants_path
		else
			render 'edit'
		end
	end

	def destroy
		@restaurant = Restaurant.find(params[:id])
		if @restaurant.user_id == current_user.id
			@restaurant.destroy
			redirect_to restaurants_path
		else
			redirect_to restaurants_path
		end
	end




end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_action :authenticate_user!

	def new
		@restaurant = Restaurant.find(params[:restaurant_id])
		if @restaurant.reviews.find_by(user_id: current_user.id).nil? && @restaurant.user_id != current_user.id
			@review = Review.new
		else
			flash[:notice] = "Sorry, you have already reviewed this restaurant."
			redirect_to restaurants_path
	end

	def create
		@restaurant = Restaurant.find(params[:restaurant_id]) 
		@review = @restaurant.reviews.create(params[:review].permit(:thoughts, :rating))
		@review.user_id = current_user.id
		@review.save
		redirect_to restaurants_path	
		end
	end



end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

	def star_rating(rating)
		return rating if rating.class == String
		("★" * rating) +  "☆" * (5 - rating)
	end

	def created(time)
			elapsed = ( (Time.now - time)/60 ).round
		if elapsed < 60 
			num, unit = elapsed, 'minutes'
		elsif 60 < elapsed && 1440 > elapsed
			num, unit = (elapsed/60), 'hours'
		else
			num, unit = (elapsed/1440), 'days'
		end
			num == 1 ? unit.chop! : nil
		return "#{num} #{unit} ago" # The method looks disgusting; I'm sure there's a way to do it recursively.
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
	<%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
<% else %>
	<%= link_to 'Sign in', new_user_session_path %>
	<%= link_to 'Sign up', new_user_registration_path %>
<% end %>
<%= notice %>
<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, :html => { :multipart => true } do |f| %>
<%= f.label :name %>
<%= f.text_area :name %>

<%= f.label :description %>
<%= f.text_area :description %>
<%= f.file_field :image %>
<%= f.submit 'Submit' %>

<% end %>

app/views/restaurants/edit.html.erb
<%= form_for @restaurant do |f| %>
<%= f.label :name %>
<%= f.text_area :name %>

<%= f.label :description %>
<%= f.text_area :description %>
<%= f.submit 'Submit' %>

<% end %>

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
    <% @restaurants.each do |restaurant| %>
        <h2> <%= link_to restaurant.name, restaurant_path(restaurant) %> </h2>
        <%= image_tag restaurant.image.url %>
        puts restaurant.inspect
        <% if current_user %>
        <% if restaurant.user_id != current_user.id %>
        <%= link_to 'Review ' + restaurant.name, new_restaurant_review_path(restaurant) %><br>
        <% end %>
        <% end %>
    <% restaurant.reviews.each do |review| %>
    	<%= review.thoughts %><br>
    	<%= link_to 'Endorse', review_endorsements_path(review), class: 'endorsements-link' %>
    	<span><%= review.endorsements.count %> endorsements</span>
    	<% end %>
    <% end %>
<% else %>
    No restaurants yet
<% end %>
<%= link_to 'Add a restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/restaurants/show.html.erb
<strong><%= @restaurant.name %></strong>
<%= image_tag @restaurant.image.url %>
<% if current_user %>
<% if @restaurant.user_id == current_user.id %>
<%= link_to 'Edit', edit_restaurant_path(@restaurant) %>
<%= link_to 'Delete', restaurant_path(@restaurant), method: :delete %>
<% end %>
<% end %>

<br>
<%= @restaurant.description %>

	<strong>Cuisine:</strong>
	<%= @restaurant.description %>
<% if @restaurant.reviews %>
<section class='reviews'>
<h2>Reviews:</h2>
<% @restaurant.reviews.each do |review| %>
<br>
<li>
		<strong>Rating:</strong>
		<%= star_rating(review.rating) %><br>
		<strong>Comment:</strong>
		<%= review.thoughts %><br>
		<em>Posted: <%= created(review.created_at) %></em>
</li>
<br>
	<% end %>
</section>
<% end %>
<%= link_to 'Add a review', new_restaurant_review_path(@restaurant) %>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
<%= f.label :thoughts %>
<%= f.text_area :thoughts %>

<%= f.label :rating %>
<%= f.select :rating, (1..5) %>
<%= f.submit 'Leave Review' %>
<% end %>